python/django/learning_site/courses/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.course_list, name='list'),
    url(r'(?P<course_pk>\d+)/(?P<step_pk>\d+)/$', views.step_detail, name='step'),
    url(r'(?P<pk>\d+)/$', views.course_detail, name='detail'),
]

python/django/learning_site/learning_site/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from . import views
from courses import views as courses_views

urlpatterns = [
    url(r'^courses/', include('courses.urls', namespace='courses')),
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.hello_world, name='hello_world'),
]

python/django/learning_site/courses/models.py
from django.db import models

# Create your models here.
class Course(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    title = models.CharField(max_length=255)
    description = models.TextField()

    def __str__(self):
        return self.title

class Step(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()
    content = models.TextField(blank=True, default='')
    order = models.IntegerField(default=0)
    course = models.ForeignKey(Course)

    class Meta:
        ordering = ['order',]

    def __str__(self):
        return self.title

python/django/learning_site/courses/views.py
from django.shortcuts import get_object_or_404, render

from .models import Course, Step

# Create your views here.
def course_list(request):
    courses = Course.objects.all()
    email = 'questions@learningsite.com'
    return render(request, 'courses/course_list.html', {'courses': courses,
                                                        'email': email})

def course_detail(request, pk):
    course = get_object_or_404(Course, pk=pk)
    return render(request, 'courses/course_detail.html', {'course': course})

def step_detail(request, course_pk, step_pk):
    step = get_object_or_404(Step, course_id=course_pk, pk=step_pk)
    return render(request, 'courses/step_detail.html', {'step': step})

python/django/learning_site/learning_site/views.py
from django.shortcuts import render

def hello_world(request):
    return render(request, 'home.html')

python/django/learning_site/courses/templates/courses/course_detail.html
{% extends "layout.html" %}
{% load humanize course_extras %}
{% block title %} {{ course.title }} {% endblock %}

{% block content %}
<article>
    <h2>{{ course.title }}</h2>
    {{ course.description|markdown_to_html }}

    <p>There are {{ course.step_set.count|apnumber }} step{{ course.step_set.count|pluralize }} in this course: {{ course.step_set.all|join:", "}}</p>

    <section>
        {% for step in course.step_set.all %}
            <h3><a href="{% url 'courses:step' course_pk=step.course.pk step_pk=step.pk %}">{{ step.title }}</a></h3>
            {{ step.description|linebreaks }}
        {% endfor %}
    </section>
</article>
{% endblock %}

python/django/learning_site/courses/templates/courses/course_list.html
{% extends "layout.html" %}
{% load static %}

{% block static %}<link rel="stylesheet" type='text/css' href="{% static 'courses/css/courses.css' %}">{% endblock %}
{% block title %}Available Courses{% endblock %}

{% block content %}
<div class="cards">
    {% for course in courses %}
    <div class="card">
        <header><a href="{% url 'courses:detail' pk=course.pk %}">{{ course.title }}</a></header>
        <div class="card-copy">
            {% if course.description|wordcount <= 5 %}
                {{ course.description|linebreaks }}
            {% else %}
                {{ course.description|truncatewords:5 }}
                <a href="{% url 'courses:detail' pk=course.pk %}">Read more</a>
            {% endif %}
            <div>Created on: {{ course.created_at|date:"F j, Y" }}</div>
        </div>
    </div>
    {% endfor %}
    <div>Have questions?  Contact us: {{ email|urlize }} </div>
</div>
{% endblock %}

python/django/learning_site/courses/templates/courses/course_nav.html
{% for course in courses %}
    <div><a href="{% url 'courses:detail' pk=course.pk %}">{{ course.title }}</a></div>
{% endfor %}

python/django/learning_site/courses/templates/courses/step_detail.html
{% extends "layout.html" %}
{% load course_extras %}

{% block title %}{{ step.title }} - {{ step.course.title }}{% endblock %}

{% block content %}
<article>
    <h2><a href="{% url 'courses:detail' pk=step.course.pk %}">{{ step.course }}</a></h2>
    <h3>{{ step.title }}</h3>
    {% with con=step.content %}
        {{ con|linebreaks }} Content: {{ con|wordcount }} words.  Estimated time to complete: {{ con|wordcount|time_estimate }} minute{{ con|wordcount|time_estimate|pluralize }}.
    {% endwith %}
</article>
{% endblock %}

python/django/learning_site/templates/home.html
{% extends "layout.html" %}

{% block title %}
Hello there!
{% endblock %}

{% block content %}
<h1>Welcome!</h1>
{% endblock %}

python/django/learning_site/templates/layout.html
<!doctype html>
{% load static %}
{% load course_extras %}
<html>
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" type='text/css' href="{% static 'css/layout.css' %}">
        {% block static %}{% endblock %}
    </head>
    <body>
        <div class="site-container">
            <div>{% nav_courses_list %}</div>
            <nav>
                <a href="{% url 'hello_world' %}">Home</a>
                <a href="{% url 'courses:list' %}">Courses</a>
            </nav>
            {% newest_course as nc %}
            <p>Check out our latest course: <a href="{% url 'courses:detail' pk=nc.pk %}">{{ nc }}</a></p>
        {% block content %}{% endblock %}
        </div>
    </body>
</html>